#!/bin/bash

set -euo pipefail

PLUGIN_BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
# shellcheck source=./lib/helpers.bash
source "${PLUGIN_BASEDIR}/lib/helpers.bash"

# if there are no artifacts uploaded from the step, the post-artifact hook won't be run
if [[ -z "${BUILDKITE_ARTIFACT_PATHS}" ]]; then
    run_plugin
fi